RESISTIVE_GROUND_HUMIDITY_PIN = 2
CAPACITIVE_GROUND_HUMIDITY_PIN = 3
LIGHT_SENSOR_PIN = 7
BUZZER_PIN = 0
GREEN_DIODE_PIN = 3
RED_DIODE_PIN = 6
YELLOW_DIODE_PIN = 5
BUTTON_PIN = 2

SENSOR_READING_ACCUMULATOR_CAPACITY = 5

DB_NAME = 'garden'
