import Adafruit_DHT

RESISTIVE_GROUND_HUMIDITY_CHANNEL = 7
CAPACITIVE_GROUND_HUMIDITY_CHANNEL = 6
LIGHT_SENSOR_CHANNEL = 5

BUTTON_PIN = 2

SENSOR_READING_ACCUMULATOR_CAPACITY = 1

DB_NAME = 'garden'

DHT_SENSOR = Adafruit_DHT.DHT22
DHT_PIN = 22
