import Adafruit_DHT

LEMON_RESISTIVE_SOIL_MOISTURE_CHANNEL = 7
LEMON_CAPACITIVE_SOIL_MOISTURE_CHANNEL = 6
LIGHT_SENSOR_CHANNEL = 5

BUTTON_PIN = 2

DB_NAME = 'garden'

DHT_SENSOR = Adafruit_DHT.DHT22
DHT_PIN = 22
